### ISSUE TITLE
0.19.1 support

### ISSUE THREAD

**Issue by zwilias** [zwilias/elm-json#14]
In order to support 0.19.1 when it is released, we need to take care of a few nits:

- [x] add 0.19.1 as a known elm version
- [ ] figure out lookup paths for cached files (currently hardcoded to 0.19.0)

**Comment by jfmengels** [comment]
FYI, the [`elm-review CLI`](https://www.npmjs.com/package/elm-review) uses `elm-json`.

To work, it creates a new elm application directory (in `elm-stuff/`), adds dependencies (using `elm-json`), builds the project then runs it.

This stops working when I have the `elm.json`'s version set to `0.19.1`, and I get the following error message.

```
-- NO VALID PACKAGE VERSION ----------------------------------------------------

Because Elm 0.19.1 is unavailable and this project depends on Elm
0.19.1, no valid set of package versions could be found.
```

Let me know if I can help, and while I'm here, thanks a lot for the tool. It has been very useful and a pleasure to use :heart:

**Comment by zwilias** [comment]
Right. I'll release a version with `0.19.1` as a supported Elm version, and figure out the lookup paths/caching in a later iteration. It's purely an optimization anyway :)

**Comment by zwilias** [comment]
@jfmengels Initial compatibility should be good now, as of [the 0.2.2 release](https://www.npmjs.com/package/elm-json/v/0.2.2)! Let me know if that works for you :)
